package sigil.provider

import spice.net.URL

/**
 * A single content block within a multimodal [[ProviderMessage.User]].
 * Separate trait so the messages list can interleave text and images
 * the way every major provider's chat API expects for multimodal input.
 *
 *   - [[MessageContent.Text]]: plain text. The workhorse — most user
 *     messages contain exactly one of these.
 *   - [[MessageContent.Image]]: an image the LLM should see, referenced
 *     by a public URL. Apps that receive uploaded images are responsible
 *     for hosting them at a fetchable URL.
 *   - [[MessageContent.ImageBytes]]: an image carried as raw base64 bytes
 *     with an explicit media type. Use this for inline images (uploaded
 *     by the user mid-conversation, generated by another tool, etc.)
 *     when there's no fetchable URL to point at.
 *
 * Providers that don't support multimodal input silently drop image
 * blocks (rather than failing). Vision-capable models render both.
 *
 * Why two variants: spice's `URL` parser is HTTP/HTTPS-oriented and
 * doesn't accept `data:` URLs (it mis-parses them as `https://` with
 * `data:image` as the host). Pre-fix the only "inline bytes" path was
 * a data URL string, but it never round-tripped through the URL type.
 * The split makes the byte path first-class and the type-level shape
 * matches what providers actually do at the wire boundary anyway —
 * Gemini emits `inlineData`, Anthropic emits `{type: "base64", …}`.
 */
sealed trait MessageContent

object MessageContent {
  case class Text(text: String) extends MessageContent
  case class Image(url: URL, altText: Option[String] = None) extends MessageContent

  /**
   * Inline image bytes carried in the request.
   *
   * @param mediaType the image MIME (`image/jpeg`, `image/png`, `image/webp`, …).
   * @param base64    the image bytes, already base64-encoded (no `data:` prefix).
   * @param altText   optional alt text the model may surface for accessibility.
   */
  case class ImageBytes(mediaType: String, base64: String, altText: Option[String] = None) extends MessageContent
}
